[
  { "id": "cre_1", "description": "Ar-Condicionado Elbrus 12.000 BTU", "unit_condition": "Bacanga", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_2", "description": "Ar-Condicionado Elbrus 12.000 BTU", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_3", "description": "Ar-Condicionado Electrolux 18.000 BTU", "unit_condition": "Centro", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_4", "description": "Ar-Condicionado Elgin 12.000 BTU", "unit_condition": "Centro", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_5", "description": "Ar-Condicionado Elgin 12.000 BTU", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_6", "description": "Ar-Condicionado Elgin 12.000 BTU", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_7", "description": "Ar-Condicionado Elgin 12.000 BTU", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_8", "description": "Ar-Condicionado Consul 12.000 BTU", "unit_condition": "Sol e Mar", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_9", "description": "Ar-Condicionado HQ 9.000 BTU", "unit_condition": "Sol e Mar", "quantity": 2, "state": "Novo", "donation": "Não" },
  { "id": "cre_10", "description": "Ar-Condicionado HQ 9.000 BTU", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_11", "description": "Ar-Condicionado Philco 18.000 BTU", "unit_condition": "Cidade Operária", "quantity": 2, "state": "Novo", "donation": "Não" },
  { "id": "cre_12", "description": "Ar-Condicionado Agratto 12.000 BTU", "unit_condition": "Cidade Operária", "quantity": 2, "state": "Novo", "donation": "Não" },
  { "id": "cre_13", "description": "Armário em Aço", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Sim" },
  { "id": "cre_14", "description": "Armário em Aço", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_15", "description": "Armário em Aço", "unit_condition": "Centro", "quantity": 1, "state": "Regular", "donation": "Não" },
  { "id": "cre_16", "description": "Armário em Aço", "unit_condition": "Centro", "quantity": 2, "state": "Avariado", "donation": "Não" },
  { "id": "cre_17", "description": "Armário em Aço", "unit_condition": "Sol e Mar", "quantity": 8, "state": "Bom", "donation": "Sim" },
  { "id": "cre_18", "description": "Armário em Aço", "unit_condition": "Cidade Operária", "quantity": 7, "state": "Bom", "donation": "Não" },
  { "id": "cre_19", "description": "Armário em MDF", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Sim" },
  { "id": "cre_20", "description": "Armário em MDF", "unit_condition": "Centro", "quantity": 1, "state": "Bom", "donation": "Sim" },
  { "id": "cre_21", "description": "Armário em MDF", "unit_condition": "Sol e Mar", "quantity": 2, "state": "Bom", "donation": "Sim" },
  { "id": "cre_22", "description": "Arquivo em Aço", "unit_condition": "Bacanga", "quantity": 3, "state": "Bom", "donation": "Não" },
  { "id": "cre_23", "description": "Arquivo em Aço", "unit_condition": "Bacanga", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_24", "description": "Arquivo em Aço", "unit_condition": "Centro", "quantity": 6, "state": "Bom", "donation": "Não" },
  { "id": "cre_25", "description": "Arquivo em Aço", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_26", "description": "Bebedouro de Coluna", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_27", "description": "Bebedouro de Coluna Esmaltec", "unit_condition": "Centro", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_28", "description": "Bebedouro de Coluna Esmaltec", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_29", "description": "Cadeira de Plástico", "unit_condition": "Bacanga", "quantity": 24, "state": "Bom", "donation": "Não" },
  { "id": "cre_30", "description": "Cadeira de Plástico", "unit_condition": "Centro", "quantity": 6, "state": "Bom", "donation": "Não" },
  { "id": "cre_31", "description": "Cadeira de Plástico", "unit_condition": "Cidade Operária", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_32", "description": "Cadeira de Plástico Branca", "unit_condition": "Bacanga", "quantity": 32, "state": "Bom", "donation": "Não" },
  { "id": "cre_33", "description": "Cadeira de Plástico Branca", "unit_condition": "Centro", "quantity": 6, "state": "Bom", "donation": "Não" },
  { "id": "cre_34", "description": "Cadeira de Plástico Branca", "unit_condition": "Sol e Mar", "quantity": 8, "state": "Bom", "donation": "Não" },
  { "id": "cre_35", "description": "Cadeira de Plástico Branca", "unit_condition": "Cidade Operária", "quantity": 8, "state": "Bom", "donation": "Não" },
  { "id": "cre_36", "description": "Cadeira de Plástico Verde", "unit_condition": "Bacanga", "quantity": 16, "state": "Bom", "donation": "Não" },
  { "id": "cre_37", "description": "Cadeira de Plástico Verde (Atendimento)", "unit_condition": "Bacanga", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_38", "description": "Cadeira de Plástico Verde (Usuário)", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_39", "description": "Cadeira de Plástico Infantil", "unit_condition": "Bacanga", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_40", "description": "Cadeira de Plástico Infantil", "unit_condition": "Centro", "quantity": 6, "state": "Bom", "donation": "Não" },
  { "id": "cre_41", "description": "Cadeira de Plástico Infantil", "unit_condition": "Sol e Mar", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_42", "description": "Cadeira de Plástico Infantil", "unit_condition": "Cidade Operária", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_43", "description": "Cadeira Palito", "unit_condition": "Bacanga", "quantity": 3, "state": "Bom", "donation": "Sim" },
  { "id": "cre_44", "description": "Cadeira Palito", "unit_condition": "Centro", "quantity": 2, "state": "Regular", "donation": "Não" },
  { "id": "cre_45", "description": "Cadeira Palito", "unit_condition": "Centro", "quantity": 3, "state": "Bom", "donation": "Não" },
  { "id": "cre_46", "description": "Cadeira Palito", "unit_condition": "Cidade Operária", "quantity": 4, "state": "Bom", "donation": "Não" },
  { "id": "cre_47", "description": "Cadeira Palito Preta", "unit_condition": "Centro", "quantity": 1, "state": "Regular", "donation": "Não" },
  { "id": "cre_48", "description": "Cadeira Palito Preta", "unit_condition": "Centro", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_49", "description": "Cadeira Palito Preta", "unit_condition": "Centro", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_50", "description": "Cadeira de Palhinha", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Regular", "donation": "Não" },
  { "id": "cre_51", "description": "Cadeira em Polímero Azul", "unit_condition": "Centro", "quantity": 3, "state": "Bom", "donation": "Sim" },
  { "id": "cre_52", "description": "Cadeira em Polímero Azul", "unit_condition": "Centro", "quantity": 3, "state": "Regular", "donation": "Sim" },
  { "id": "cre_53", "description": "Cadeira em Polímero Azul", "unit_condition": "Sol e Mar", "quantity": 38, "state": "Bom", "donation": "Sim" },
  { "id": "cre_54", "description": "Cadeira em Polímero Preta", "unit_condition": "Sol e Mar", "quantity": 15, "state": "Bom", "donation": "Sim" },
  { "id": "cre_55", "description": "Cadeira Giratória Azul", "unit_condition": "Centro", "quantity": 1, "state": "Regular", "donation": "Não" },
  { "id": "cre_56", "description": "Cadeira Giratória Azul", "unit_condition": "Centro", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_57", "description": "Cadeira Giratória Azul", "unit_condition": "Cidade Operária", "quantity": 6, "state": "Bom", "donation": "Não" },
  { "id": "cre_58", "description": "Cadeira Giratória Azul", "unit_condition": "Cidade Operária", "quantity": 2, "state": "Avariado", "donation": "Não" },
  { "id": "cre_59", "description": "Cadeira Tipo Presidente Preta", "unit_condition": "Bacanga", "quantity": 1, "state": "Regular", "donation": "Não" },
  { "id": "cre_60", "description": "Cadeira Presidente", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_61", "description": "Cadeira", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_62", "description": "Longarina Preta 3 Lugares", "unit_condition": "Sol e Mar", "quantity": 4, "state": "Bom", "donation": "Sim" },
  { "id": "cre_63", "description": "Longarina 5 Lugares", "unit_condition": "Cidade Operária", "quantity": 3, "state": "Novo", "donation": "Não" },
  { "id": "cre_64", "description": "Longarina 3 Lugares Azul", "unit_condition": "Cidade Operária", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_65", "description": "Longarina 3 Lugares Azul", "unit_condition": "Cidade Operária", "quantity": 2, "state": "Regular", "donation": "Não" },
  { "id": "cre_66", "description": "Computador Positivo", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_67", "description": "CPU Positivo Completo", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_68", "description": "Estante em Aço", "unit_condition": "Bacanga", "quantity": 4, "state": "Regular", "donation": "Não" },
  { "id": "cre_69", "description": "Estante em Aço", "unit_condition": "Centro", "quantity": 2, "state": "Regular", "donation": "Não" },
  { "id": "cre_70", "description": "Estante em Aço", "unit_condition": "Centro", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_71", "description": "Estante em Aço", "unit_condition": "Cidade Operária", "quantity": 5, "state": "Bom", "donation": "Não" },
  { "id": "cre_72", "description": "Fogão 4 Bocas", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_73", "description": "Fogão 4 Bocas", "unit_condition": "Centro", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_74", "description": "Fogão 4 Bocas", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_75", "description": "Fogão 4 Bocas", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_76", "description": "Geladeira Esmaltec", "unit_condition": "Bacanga", "quantity": 2, "state": "Novo", "donation": "Não" },
  { "id": "cre_77", "description": "Geladeira Esmaltec", "unit_condition": "Centro", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_78", "description": "Geladeira Esmaltec", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_79", "description": "Geladeira Esmaltec", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_80", "description": "Frigobar", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_81", "description": "Impressora OfficeJet Pro 8600", "unit_condition": "Centro", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_82", "description": "Impressora Brother HL1202", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_83", "description": "Mesa para Escritório", "unit_condition": "Bacanga", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_84", "description": "Mesa para Escritório", "unit_condition": "Centro", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_85", "description": "Mesa para Escritório", "unit_condition": "Centro", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_86", "description": "Mesa para Escritório", "unit_condition": "Sol e Mar", "quantity": 3, "state": "Novo", "donation": "Não" },
  { "id": "cre_87", "description": "Mesa para Escritório", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Bom", "donation": "Sim" },
  { "id": "cre_88", "description": "Mesa para Escritório", "unit_condition": "Cidade Operária", "quantity": 3, "state": "Novo", "donation": "Não" },
  { "id": "cre_89", "description": "Mesa para Escritório", "unit_condition": "Cidade Operária", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_90", "description": "Mesa para Escritório (Atendimento)", "unit_condition": "Bacanga", "quantity": 5, "state": "Bom", "donation": "Não" },
  { "id": "cre_91", "description": "Mesa para Escritório (Atendimento)", "unit_condition": "Bacanga", "quantity": 1, "state": "Regular", "donation": "Não" },
  { "id": "cre_92", "description": "Mesa para Escritório (Atendimento)", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_93", "description": "Mesa para Escritório com 2 Gavetas", "unit_condition": "Bacanga", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_94", "description": "Mesa para Escritório com 2 Gavetas", "unit_condition": "Centro", "quantity": 3, "state": "Bom", "donation": "Não" },
  { "id": "cre_95", "description": "Mesa para Escritório com 2 Gavetas", "unit_condition": "Centro", "quantity": 1, "state": "Regular", "donation": "Não" },
  { "id": "cre_96", "description": "Mesa para Escritório com 2 Gavetas", "unit_condition": "Sol e Mar", "quantity": 3, "state": "Bom", "donation": "Sim" },
  { "id": "cre_97", "description": "Mesa para Escritório com 2 Gavetas", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_98", "description": "Mesa para Escritório com 2 Gavetas (Atendimento)", "unit_condition": "Centro", "quantity": 2, "state": "Regular", "donation": "Sim" },
  { "id": "cre_99", "description": "Mesa para Escritório com 3 Gavetas", "unit_condition": "Sol e Mar", "quantity": 2, "state": "Novo", "donation": "Não" },
  { "id": "cre_100", "description": "Mesa para Escritório com 3 Gavetas", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_101", "description": "Mesa para Digitador", "unit_condition": "Cidade Operária", "quantity": 3, "state": "Bom", "donation": "Não" },
  { "id": "cre_102", "description": "Mesa de Plástico", "unit_condition": "Centro", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_103", "description": "Mesa de Plástico", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_104", "description": "Mesa de Plástico Branca", "unit_condition": "Bacanga", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_105", "description": "Mesa de Plástico Branca", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_106", "description": "Mesa de Plástico Branca", "unit_condition": "Cidade Operária", "quantity": 2, "state": "Bom", "donation": "Não" },
  { "id": "cre_107", "description": "Mesa de Plástico Infantil", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_108", "description": "Mesa de Plástico Infantil", "unit_condition": "Centro", "quantity": 3, "state": "Bom", "donation": "Não" },
  { "id": "cre_109", "description": "Mesa de Plástico Infantil", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_110", "description": "Mesa de Plástico Infantil", "unit_condition": "Cidade Operária", "quantity": 4, "state": "Bom", "donation": "Não" },
  { "id": "cre_111", "description": "Mesa em L", "unit_condition": "Bacanga", "quantity": 1, "state": "Regular", "donation": "Não" },
  { "id": "cre_112", "description": "Mesa em L", "unit_condition": "Sol e Mar", "quantity": 2, "state": "Novo", "donation": "Não" },
  { "id": "cre_113", "description": "Mesa para Computador", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_114", "description": "Mesa Redonda", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_115", "description": "Mesa Redonda", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_116", "description": "Mesa Redonda (Atendimento)", "unit_condition": "Centro", "quantity": 1, "state": "Avariado", "donation": "Não" },
  { "id": "cre_117", "description": "Mesa para Reunião", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Bom", "donation": "Sim" },
  { "id": "cre_118", "description": "Mesa Tipo Reunião", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Regular", "donation": "Não" },
  { "id": "cre_119", "description": "Ponto Eletrônico", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_120", "description": "Ponto Eletrônico", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_121", "description": "Televisão HQ", "unit_condition": "Bacanga", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_122", "description": "Televisão HQ", "unit_condition": "Centro", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_123", "description": "Televisão HQ", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_124", "description": "Televisão HQ", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_125", "description": "Totem", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_126", "description": "Ventilador de Coluna", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_127", "description": "Ventilador de Parede", "unit_condition": "Bacanga", "quantity": 1, "state": "Bom", "donation": "Não" },
  { "id": "cre_128", "description": "Ventilador de Parede", "unit_condition": "Centro", "quantity": 3, "state": "Novo", "donation": "Não" },
  { "id": "cre_129", "description": "Ventilador de Parede", "unit_condition": "Sol e Mar", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_130", "description": "Rack", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_131", "description": "Switch", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Novo", "donation": "Não" },
  { "id": "cre_132", "description": "Quadro Branco", "unit_condition": "Cidade Operária", "quantity": 4, "state": "Bom", "donation": "Não" },
  { "id": "cre_133", "description": "Nobreak", "unit_condition": "Cidade Operária", "quantity": 1, "state": "Bom", "donation": "Sim" }
]
